### ISSUE TITLE
Failed to push 

### ISSUE THREAD

**Issue by kayth1** [loewenfels/dep-graph-releaser#42]
```
To ssh://*************************************
 ! [rejected]            HEAD -> master (fetch first)
error: failed to push some refs to 'ssh://*****************************
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

As far as I understand, DGR builds the project with the new dependency and if build is fine, DGR wants to push the change with the updated POM. It looks like someone pushed other changes meanwhile. Happens in an active company. So in this case the failure message may should be clear or DGR should automatically re-trigger this job (maybe with an info message) because the user would do exactly the same anyway.

**Comment by robstoll** [comment]
The jenkins job as such is not part of DGR and can be freely adopted as one wishes. Hence I am going to close this issue. The error you mentioned happens in the commit stage (assuming you are using the job template as described [here](https://github.com/loewenfels/dep-graph-releaser/wiki/Jenkins-Server) we have the following stages: checkout, fetch pom-runner, update, test-compile, commit). IMO it is already clear enough where the problem occurred and git explains why (I guess your assumption is totally correct, someone pushed in the meanwhile). 
You could wrap everything in a `retry` block so that it is executed again but of course, someone else could already push in the meantime again. I think it is development process specific how you want to tackle this problem. Another solution would be to do a `git pull` before doing the commit (with the slight chance that test-compile would fail if you would rerun it.)
